### PR TITLE
add column to social block on mobile & center buttons

### PR DESCRIPTION
**Pull request by Arhell**
https://github.com/cakephp/sphinxtheme/issues/22

### CODE REVIEW

**Comment by Arhell** [comment]
cc @markstory

**Comment by Arhell** [comment]
cc @othercorey

**Comment by othercorey** [comment]
We have to deploy the theme with each fix. He will merge it when ready to deploy.

**Comment by Arhell** [comment]
and add this fix https://github.com/cakephp/sphinxtheme/issues/24

**Pull request merged**
